/* Auto-generated by tools/generate-nav-tree.cjs — do not edit by hand */
(function () {
  'use strict';
  window.WM_NAV_TREE = {
  "hubs": [
    {
      "slug": "aluminium-windows",
      "label": "Aluminium Windows",
      "href": "products/aluminium-windows",
      "children": [
        {
          "label": "All Aluminium Windows",
          "href": "products/aluminium-windows"
        },
        {
          "label": "2 Track Aluminium Window Price",
          "href": "products/aluminium-windows/2-track-aluminium-window-price"
        },
        {
          "label": "2 Track French Sliding Door",
          "href": "products/aluminium-windows/2-track-french-sliding-door"
        },
        {
          "label": "3 Track Sliding Window",
          "href": "products/aluminium-windows/3-track-sliding-window"
        },
        {
          "label": "4 Track Aluminium Sliding Window Price",
          "href": "products/aluminium-windows/4-track-sliding-window-price"
        },
        {
          "label": "Aluminium Casement Window Price",
          "href": "products/aluminium-windows/aluminium-casement-window-price"
        },
        {
          "label": "Aluminium Sliding Window",
          "href": "products/aluminium-windows/aluminium-sliding-window"
        },
        {
          "label": "Aluminium System Window Price",
          "href": "products/aluminium-windows/aluminium-system-window-price"
        },
        {
          "label": "Bengaluru",
          "href": "products/aluminium-windows/aluminium-window-price-bangalore"
        },
        {
          "label": "Chandigarh",
          "href": "products/aluminium-windows/aluminium-window-price-chandigarh"
        },
        {
          "label": "Delhi NCR",
          "href": "products/aluminium-windows/aluminium-window-price-delhi"
        },
        {
          "label": "French Door Georgian Bar",
          "href": "products/aluminium-windows/french-door-georgian-bar"
        },
        {
          "label": "Georgian Grill Casement Door",
          "href": "products/aluminium-windows/georgian-grill-casement-door"
        },
        {
          "label": "Hyderabad ₹/sqft",
          "href": "products/aluminium-windows/aluminium-window-price-hyderabad"
        },
        {
          "label": "Mumbai",
          "href": "products/aluminium-windows/aluminium-window-price-mumbai"
        },
        {
          "label": "Pune",
          "href": "products/aluminium-windows/aluminium-window-price-pune"
        },
        {
          "label": "Slim Aluminium Window Price Luxury",
          "href": "products/aluminium-windows/slim-aluminium-window-price-luxury"
        },
        {
          "label": "Slim Entrance Glass Door",
          "href": "products/aluminium-windows/slim-entrance-glass-door"
        },
        {
          "label": "Slim System Window Price",
          "href": "products/aluminium-windows/slim-system-window-price"
        },
        {
          "label": "Slimline Aluminium Window",
          "href": "products/aluminium-windows/slimline-aluminium-window"
        },
        {
          "label": "System Casement Window Price",
          "href": "products/aluminium-windows/system-casement-window-price"
        },
        {
          "label": "System Sliding Window Price",
          "href": "products/aluminium-windows/system-sliding-window-price"
        },
        {
          "label": "Top Hung Casement Window",
          "href": "products/aluminium-windows/top-hung-casement-window"
        },
        {
          "label": "Vijayawada",
          "href": "products/aluminium-windows/aluminium-window-price-vijayawada"
        },
        {
          "label": "Visakhapatnam",
          "href": "products/aluminium-windows/aluminium-window-price-visakhapatnam"
        },
        {
          "label": "Warangal",
          "href": "products/aluminium-windows/aluminium-window-price-warangal"
        }
      ]
    },
    {
      "slug": "telescope-windows",
      "label": "Telescopic Doors",
      "href": "products/telescope-windows",
      "children": [
        {
          "label": "All Telescopic Doors",
          "href": "products/telescope-windows"
        },
        {
          "label": "Telescopic Slim Sliding Door",
          "href": "products/telescope-windows/telescopic-slim-sliding-door"
        }
      ]
    },
    {
      "slug": "folding-systems",
      "label": "Folding Systems",
      "href": "products/folding-systems",
      "children": [
        {
          "label": "All Folding Systems",
          "href": "products/folding-systems"
        },
        {
          "label": "Fold Bifold Aluminium Doors",
          "href": "products/folding-systems/fold-bifold-aluminium-doors"
        },
        {
          "label": "Fold Sliding Window System",
          "href": "products/folding-systems/fold-sliding-window-system"
        }
      ]
    },
    {
      "slug": "pergola",
      "label": "Pergolas",
      "href": "products/pergola",
      "children": [
        {
          "label": "All Pergolas",
          "href": "products/pergola"
        },
        {
          "label": "Aluminium Pergola",
          "href": "products/pergola/aluminium-pergola"
        },
        {
          "label": "Glass Roof Pergola Price in India",
          "href": "products/pergola/glass-skylight"
        },
        {
          "label": "Motorized Pergola Roof Price in India",
          "href": "products/pergola/retractable-pergola"
        },
        {
          "label": "Profile Iron Canopy",
          "href": "products/pergola/profile-iron-canopy"
        },
        {
          "label": "Profile Pergola",
          "href": "products/pergola/profile-pergola"
        }
      ]
    },
    {
      "slug": "metal-louvers",
      "label": "Metal Louvers",
      "href": "products/metal-louvers",
      "children": [
        {
          "label": "All Metal Louvers",
          "href": "products/metal-louvers"
        },
        {
          "label": "Aluminium Facade Louver Price",
          "href": "products/metal-louvers/aluminium-facade-louver-price"
        },
        {
          "label": "Aluminium Louver Design Building",
          "href": "products/metal-louvers/aluminium-louver-design-building"
        },
        {
          "label": "Aluminium Louvre 100x50mm Price",
          "href": "products/metal-louvers/aluminium-louvre-100x50mm-price"
        },
        {
          "label": "Aluminium Louvre 75x38mm Price",
          "href": "products/metal-louvers/aluminium-louvre-75x38mm-price"
        },
        {
          "label": "Ceiling Pergola Louvers",
          "href": "products/metal-louvers/ceiling-pergola-louvers"
        },
        {
          "label": "Commercial Building Louvers",
          "href": "products/metal-louvers/commercial-building-louvers"
        },
        {
          "label": "Curved Architectural Louvers",
          "href": "products/metal-louvers/curved-architectural-louvers"
        },
        {
          "label": "Louver Canopy Facade",
          "href": "products/metal-louvers/louver-canopy-facade"
        },
        {
          "label": "Louver Installation Guide",
          "href": "products/metal-louvers/louver-installation-guide"
        },
        {
          "label": "Louver Price Delhi",
          "href": "products/metal-louvers/louver-price-delhi"
        },
        {
          "label": "Louver Price Hyderabad",
          "href": "products/metal-louvers/louver-price-hyderabad"
        },
        {
          "label": "Louver Price Jaipur",
          "href": "products/metal-louvers/louver-price-jaipur"
        },
        {
          "label": "Motorized Louver Price India",
          "href": "products/metal-louvers/motorized-louver-price-india"
        },
        {
          "label": "Perforated Aluminium Panel Price",
          "href": "products/metal-louvers/perforated-aluminium-panel-price"
        },
        {
          "label": "Wooden Finish Aluminium Louvers",
          "href": "products/metal-louvers/wooden-finish-aluminium-louvers"
        }
      ]
    },
    {
      "slug": "mirror-profiles",
      "label": "Mirror Profiles",
      "href": "products/mirror-profiles/",
      "children": [
        {
          "label": "All Mirror Profiles",
          "href": "products/mirror-profiles"
        },
        {
          "label": "Aluminium Mirror Frame Designs",
          "href": "products/mirror-profiles/aluminium-mirror-frame-designs"
        },
        {
          "label": "Backlit Mirror Profile Price",
          "href": "products/mirror-profiles/backlit-mirror-profile-price"
        },
        {
          "label": "Custom Mirror Profile",
          "href": "products/mirror-profiles/custom-mirror-profile"
        },
        {
          "label": "D-Type Half Round LED Mirror Price",
          "href": "products/mirror-profiles/led-mirror-profile-delhi"
        },
        {
          "label": "Led Bathroom Mirror Profile",
          "href": "products/mirror-profiles/led-bathroom-mirror-profile"
        },
        {
          "label": "Led Mirror Profile Hyderabad",
          "href": "products/mirror-profiles/led-mirror-profile-hyderabad"
        },
        {
          "label": "Led Mirror Profile Price",
          "href": "products/mirror-profiles/led-mirror-profile-price"
        },
        {
          "label": "Mirror Profile Price Per Foot",
          "href": "products/mirror-profiles/mirror-profile-price-per-foot"
        },
        {
          "label": "Mirror Profile Without Led",
          "href": "products/mirror-profiles/mirror-profile-without-led"
        },
        {
          "label": "Motion Sensor Mirror Profile",
          "href": "products/mirror-profiles/motion-sensor-mirror-profile"
        },
        {
          "label": "Rectangular Mirror Profile",
          "href": "products/mirror-profiles/rectangular-mirror-profile"
        },
        {
          "label": "Round Mirror Profile",
          "href": "products/mirror-profiles/round-mirror-profile"
        },
        {
          "label": "Touch Sensor Mirror Profile",
          "href": "products/mirror-profiles/touch-sensor-mirror-profile"
        },
        {
          "label": "Wardrobe Mirror Profile",
          "href": "products/mirror-profiles/wardrobe-mirror-profile"
        }
      ]
    },
    {
      "slug": "shower-partitions",
      "label": "Shower Partitions",
      "href": "products/shower-partitions",
      "children": [
        {
          "label": "All Shower Partitions",
          "href": "products/shower-partitions"
        },
        {
          "label": "Black Profile Shower Partition",
          "href": "products/shower-partitions/black-profile-shower-partition"
        },
        {
          "label": "Frameless Shower Partition",
          "href": "products/shower-partitions/frameless-shower-partition"
        },
        {
          "label": "Frosted Glass Bathroom Door",
          "href": "products/shower-partitions/frosted-glass-bathroom-door"
        },
        {
          "label": "Premium Black Profile Shower",
          "href": "products/shower-partitions/premium-black-profile-shower"
        },
        {
          "label": "Slim Frame Shower Partition",
          "href": "products/shower-partitions/slim-frame-shower-partition"
        }
      ]
    },
    {
      "slug": "elevation-cladding",
      "label": "Elevation Cladding",
      "href": "products/elevation-cladding",
      "children": [
        {
          "label": "All Elevation Cladding",
          "href": "products/elevation-cladding"
        },
        {
          "label": "Hpl Acp Elevation Cladding",
          "href": "products/elevation-cladding/hpl-acp-elevation-cladding"
        },
        {
          "label": "Hpl Exterior Cladding",
          "href": "products/elevation-cladding/hpl-exterior-cladding"
        }
      ]
    },
    {
      "slug": "glass-elevation",
      "label": "Glass Elevation",
      "href": "products/glass-elevation",
      "children": [
        {
          "label": "All Glass Elevation",
          "href": "products/glass-elevation"
        },
        {
          "label": "Glass — Bengaluru",
          "href": "products/glass-elevation/glass-elevation-price-bangalore"
        },
        {
          "label": "Glass — Chandigarh",
          "href": "products/glass-elevation/glass-elevation-price-chandigarh"
        },
        {
          "label": "Glass — Delhi NCR",
          "href": "products/glass-elevation/glass-elevation-price-delhi"
        },
        {
          "label": "Glass — Mumbai",
          "href": "products/glass-elevation/glass-elevation-price-mumbai"
        },
        {
          "label": "Glass — Pune",
          "href": "products/glass-elevation/glass-elevation-price-pune"
        },
        {
          "label": "Glass — Vijayawada",
          "href": "products/glass-elevation/glass-elevation-price-vijayawada"
        },
        {
          "label": "Glass — Visakhapatnam",
          "href": "products/glass-elevation/glass-elevation-price-visakhapatnam"
        },
        {
          "label": "Glass — Warangal",
          "href": "products/glass-elevation/glass-elevation-price-warangal"
        }
      ]
    },
    {
      "slug": "glass-railing",
      "label": "Glass Railing",
      "href": "products/glass-railing",
      "children": [
        {
          "label": "All Glass Railing",
          "href": "products/glass-railing"
        },
        {
          "label": "Balcony Glass Railing",
          "href": "products/glass-railing/balcony-glass-railing"
        },
        {
          "label": "Staircase Glass Railing",
          "href": "products/glass-railing/staircase-glass-railing"
        }
      ]
    },
    {
      "slug": "grills",
      "label": "Safety Grills",
      "href": "products/grills",
      "children": [
        {
          "label": "All Safety Grills",
          "href": "products/grills"
        },
        {
          "label": "Aluminium Window Grills",
          "href": "products/grills/aluminium-window-grills"
        },
        {
          "label": "Balcony Safety Grills",
          "href": "products/grills/balcony-safety-grills"
        },
        {
          "label": "Iron Grill ( Iron Window Grill ) Price",
          "href": "products/grills/iron-safety-grills"
        },
        {
          "label": "Staircase Balustrade Grills",
          "href": "products/grills/staircase-balustrade-grills"
        },
        {
          "label": "Window Safety Grills",
          "href": "products/grills/window-safety-grills"
        }
      ]
    }
  ],
  "site": [
    {
      "label": "Product catalog",
      "href": "catalog"
    },
    {
      "label": "All calculators",
      "href": "calculators"
    },
    {
      "label": "Blog & guides",
      "href": "blog"
    },
    {
      "label": "About WoodenMax",
      "href": "about"
    },
    {
      "label": "Case studies",
      "href": "about/case-study-makobrew-jubilee-hills"
    },
    {
      "label": "Contact / site visit",
      "href": "contact"
    },
    {
      "label": "Warranty policy",
      "href": "policies/warranty-policy"
    },
    {
      "label": "GST & transport",
      "href": "policies/gst-transport-policy"
    }
  ]
};
})();
